
package com.soa.ws.tp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceCompositeImplService", targetNamespace = "http://tp.ws.soa.com/", wsdlLocation = "http://localhost:5678/composite?wsdl")
public class WebServiceCompositeImplService
    extends Service
{

    private final static URL WEBSERVICECOMPOSITEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICECOMPOSITEIMPLSERVICE_EXCEPTION;
    private final static QName WEBSERVICECOMPOSITEIMPLSERVICE_QNAME = new QName("http://tp.ws.soa.com/", "WebServiceCompositeImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5678/composite?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICECOMPOSITEIMPLSERVICE_WSDL_LOCATION = url;
        WEBSERVICECOMPOSITEIMPLSERVICE_EXCEPTION = e;
    }

    public WebServiceCompositeImplService() {
        super(__getWsdlLocation(), WEBSERVICECOMPOSITEIMPLSERVICE_QNAME);
    }

    public WebServiceCompositeImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICECOMPOSITEIMPLSERVICE_QNAME, features);
    }

    public WebServiceCompositeImplService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICECOMPOSITEIMPLSERVICE_QNAME);
    }

    public WebServiceCompositeImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICECOMPOSITEIMPLSERVICE_QNAME, features);
    }

    public WebServiceCompositeImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceCompositeImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceComposite
     */
    @WebEndpoint(name = "WebServiceCompositeImplPort")
    public WebServiceComposite getWebServiceCompositeImplPort() {
        return super.getPort(new QName("http://tp.ws.soa.com/", "WebServiceCompositeImplPort"), WebServiceComposite.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceComposite
     */
    @WebEndpoint(name = "WebServiceCompositeImplPort")
    public WebServiceComposite getWebServiceCompositeImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tp.ws.soa.com/", "WebServiceCompositeImplPort"), WebServiceComposite.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICECOMPOSITEIMPLSERVICE_EXCEPTION!= null) {
            throw WEBSERVICECOMPOSITEIMPLSERVICE_EXCEPTION;
        }
        return WEBSERVICECOMPOSITEIMPLSERVICE_WSDL_LOCATION;
    }

}
