
package com.soa.ws.tp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceComposite", targetNamespace = "http://tp.ws.soa.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceComposite {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifCategProduct", targetNamespace = "http://tp.ws.soa.com/", className = "com.soa.ws.tp.VerifCategProduct")
    @ResponseWrapper(localName = "verifCategProductResponse", targetNamespace = "http://tp.ws.soa.com/", className = "com.soa.ws.tp.VerifCategProductResponse")
    @Action(input = "http://tp.ws.soa.com/WebServiceComposite/verifCategProductRequest", output = "http://tp.ws.soa.com/WebServiceComposite/verifCategProductResponse")
    public String verifCategProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
